# Generated by Django 4.1.3 on 2022-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ImageField(choices=[(0, 'Teacher'), (1, 'Student'), (2, 'Stuff')], default=1, upload_to=''),
        ),
    ]
